# Generated by Django 3.2.3 on 2021-05-30 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_office'),
    ]

    operations = [
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('code', models.CharField(max_length=20, null=True, unique=True)),
                ('address', models.CharField(max_length=100, null=True)),
                ('office_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.office')),
            ],
        ),
    ]
