# Generated by Django 3.2.3 on 2021-06-05 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_warehouse'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.RemoveField(
            model_name='warehouse',
            name='office_id',
        ),
        migrations.DeleteModel(
            name='Office',
        ),
        migrations.DeleteModel(
            name='Warehouse',
        ),
    ]
