# Generated by Django 3.2.3 on 2021-06-05 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='office',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='trader',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
