# Generated by Django 3.2.3 on 2021-06-05 12:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0006_auto_20210605_1802'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryorder',
            name='note_details',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='storagereceipt',
            name='note_details',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='storagereceipt',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='deliveryorder',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='trader',
            name='date_added',
            field=models.DateField(auto_now=True),
        ),
    ]
